### ISSUE TITLE
User Side Wireframing

### ISSUE THREAD

**Issue by talhaskd** [Waleed-abdullah/IoT-Fuzzing-FYP#6]

**Comment by talhaskd** [comment]
Updates:
- User-side dashboard wireframe completed
- Review needed @moezAhmad @Waleed-abdullah 

https://www.figma.com/file/SJ1gKJYLNbtYt3AYOzzMzd/FYP---Fitness-Platform?type=design&node-id=0%3A1&mode=design&t=LqtwUt3Ib9vmSFUz-1

**Comment by talhaskd** [comment]
Updates :

- User-side wireframing completed
- Need to get some feedback from a small group of users
- Review pending @moezAhmad @Waleed-abdullah 
- Usability Testing started

https://www.figma.com/file/SJ1gKJYLNbtYt3AYOzzMzd/FYP---Fitness-Platform?type=design&node-id=0%3A1&mode=design&t=Nu4IVRup7Q2OK44K-1

**Comment by Waleed-abdullah** [comment]
looks good @talhaskd, I think we have received enough responses, can you check out the suggestions
